import type { BoxesDocument } from "@/ports/boxes/kernel";
import type { Point, Shape, ShapeColor } from "@/ports/boxes/drawing";

export function renderBoxesDocumentSvg(document: BoxesDocument): string {
  const width = roundForSvg(document.width);
  const height = roundForSvg(document.height);
  const shapes = renderLayeredShapes(document.shapes);

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" width="${width}mm" height="${height}mm" viewBox="0 0 ${width} ${height}">
  <title>Nukit Open Air Purifier Browser Cut Sheet</title>
  <desc>Generated by the TypeScript Boxes.py port layer. Layers: cut, inner-cut, engrave-labels, reference.</desc>
  <style>
    .cut { fill: none; stroke: #0b0b0b; stroke-width: 0.2; stroke-linecap: round; stroke-linejoin: round; }
    .inner-cut { fill: none; stroke: #1e63ff; stroke-width: 0.18; stroke-linecap: round; stroke-linejoin: round; }
    .annotation { fill: #c32121; font-family: Arial, sans-serif; font-size: 6px; text-anchor: middle; dominant-baseline: middle; }
    .reference { fill: none; stroke: #0b0b0b; stroke-width: 0.2; }
  </style>
${shapes}
</svg>`;
}

function renderLayeredShapes(shapes: readonly Shape[]): string {
  const layers: Array<{ color: ShapeColor; id: string; label: string; operation: string }> = [
    { color: "cut", id: "cut", label: "Cut outer profiles", operation: "cut" },
    { color: "inner-cut", id: "inner-cut", label: "Cut holes and slots", operation: "cut" },
    { color: "annotation", id: "engrave-labels", label: "Engrave labels", operation: "engrave" },
    { color: "reference", id: "reference", label: "Reference scale", operation: "reference" },
  ];

  return layers
    .map((layer) => {
      const layerShapes = shapes.filter((shape) => shape.color === layer.color);
      if (layerShapes.length === 0) {
        return "";
      }
      return `  <g id="${layer.id}" inkscape:groupmode="layer" inkscape:label="${layer.label}" data-operation="${layer.operation}">
${layerShapes.map(renderShape).join("\n")}
  </g>`;
    })
    .filter(Boolean)
    .join("\n");
}

function renderShape(shape: Shape): string {
  if (shape.type === "path") {
    return `    <path class="${shapeClass(shape.color)}" d="${renderPathData(shape.points, shape.closed)}" />`;
  }
  if (shape.type === "circle") {
    return `    <circle class="${shapeClass(shape.color)}" cx="${roundForSvg(shape.cx)}" cy="${roundForSvg(
      shape.cy,
    )}" r="${roundForSvg(shape.radius)}" />`;
  }
  if (shape.type === "rect") {
    return `    <rect class="${shapeClass(shape.color)}" x="${roundForSvg(shape.x)}" y="${roundForSvg(
      shape.y,
    )}" width="${roundForSvg(shape.width)}" height="${roundForSvg(shape.height)}" />`;
  }
  if (shape.type === "rounded-rect") {
    return `    <rect class="${shapeClass(shape.color)}" x="${roundForSvg(shape.x)}" y="${roundForSvg(
      shape.y,
    )}" width="${roundForSvg(shape.width)}" height="${roundForSvg(shape.height)}" rx="${roundForSvg(
      shape.radius,
    )}" ry="${roundForSvg(shape.radius)}" />`;
  }
  return `    <text class="${shapeClass(shape.color)}" x="${roundForSvg(shape.x)}" y="${roundForSvg(
    shape.y,
  )}" font-size="${roundForSvg(shape.fontSize)}">${escapeXml(shape.text)}</text>`;
}

function shapeClass(color: ShapeColor): string {
  return color;
}

function renderPathData(points: readonly Point[], closed: boolean): string {
  const [first, ...rest] = points;
  if (first === undefined) {
    return "";
  }
  const commands = [`M ${roundForSvg(first.x)} ${roundForSvg(first.y)}`];
  commands.push(...rest.map((point) => `L ${roundForSvg(point.x)} ${roundForSvg(point.y)}`));
  if (closed) {
    commands.push("Z");
  }
  return commands.join(" ");
}

function roundForSvg(value: number): string {
  return value.toFixed(2).replace(/0+$/, "").replace(/\.$/, "");
}

function escapeXml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&apos;");
}
