import { describe, expect, test } from "bun:test";
import {
  applyFilterPreset,
  createLaserSvg,
  createLayout,
  customFilterPresetId,
  decodeSettings,
  defaultSettings,
  encodeSettings,
  filterSelectionDimensions,
  filterPresets,
  normalizeSettings,
} from "../src/airPurifier";
import { createAssemblyModel } from "../src/assemblyModel";
import { generateAirPurifier } from "../src/boxes/generators/airPurifier";
import { evaluateBuildDiagnostics, summarizeBuildReadiness } from "../src/buildDiagnostics";
import { createAirPurifierCutPanels } from "../src/airPurifierPanels";
import { edgeSections } from "../src/cutGeometry";
import {
  createPrintableKit,
  createPrintableThreeMfExport,
  findPrintVolumePreset,
  partFitsPrintBed,
  printVolumePresets,
  type PrintVolumePresetId,
} from "../src/printableKit";

describe("AirPurifier Boxes.py port", () => {
  test("uses the generated Boxes document for summary and SVG output", () => {
    const layout = createLayout(defaultSettings);
    const svg = createLaserSvg(layout);

    expect(layout.summary.sheetWidth).toBe(layout.cutSheet.width);
    expect(layout.summary.sheetHeight).toBe(layout.cutSheet.height);
    expect(svg).toContain("<svg");
    expect(svg).toContain("Generated by the TypeScript Boxes.py port layer.");
    expect(svg).toContain('inkscape:label="Cut outer profiles"');
    expect(svg).toContain('data-operation="engrave"');
    expect(svg).toContain("100.0mm, burn:0.10mm");
    expect(readNumericSvgAttribute(svg, "width")).toBeCloseTo(layout.cutSheet.width);
    expect(readNumericSvgAttribute(svg, "height")).toBeCloseTo(layout.cutSheet.height);
  });

  test("translates AirPurifier fan holes into browser-side cut geometry", () => {
    const generator = generateAirPurifier(defaultSettings);
    const document = generator.toDocument();
    const circles = document.shapes.filter((shape) => shape.type === "circle");
    const cutRects = document.shapes.filter((shape) => shape.type === "rect" && shape.color === "cut");
    const slotRects = document.shapes.filter((shape) => shape.type === "rect" && shape.color === "inner-cut");

    expect(circles).toHaveLength(30);
    expect(cutRects.length).toBeGreaterThanOrEqual(20);
    expect(slotRects.length).toBeGreaterThan(200);
  });

  test("uses cut panel outlines as the SVG and 3D preview source of truth", () => {
    const layout = createLayout(defaultSettings);
    const svg = createLaserSvg(layout);
    const outerPathShapes = layout.cutSheet.shapes.filter((shape) => shape.type === "path" && shape.color === "cut");
    const innerPathShapes = layout.cutSheet.shapes.filter((shape) => shape.type === "path" && shape.color === "inner-cut");
    const fanPanels = layout.cutPanels.filter((panel) => panel.cuts.some((cut) => cut.type === "circle" && cut.role === "fan"));
    const assembledPanels = layout.cutPanels.filter(
      (panel) => panel.assembly?.type === "placed" && panel.assembly.role !== "filter-frame-panel",
    );

    expect(outerPathShapes).toHaveLength(layout.cutPanels.length);
    expect(innerPathShapes.length).toBeGreaterThan(500);
    expect(layout.cutSheet.shapes.some((shape) => shape.type === "circle" || shape.type === "rect")).toBe(false);
    expect(svg).toContain("<path");
    expect(fanPanels).toHaveLength(2);
    expect(assembledPanels.map((panel) => panel.id).sort()).toEqual([
      "bottom-fan-wall",
      "left-side-wall",
      "right-side-wall",
      "top-fan-wall",
    ]);
    expect(layout.cutPanels.every((panel) => panel.outline.length > 4)).toBe(true);
  });

  test("matches upstream AirPurifier layout direction and burn-corrected inner cuts", () => {
    const layout = createLayout(defaultSettings);
    const firstPanel = layout.cutPanels[0];
    const secondPanel = layout.cutPanels[1];
    const sidePanel = requiredPanel(layout.cutPanels, "left-side-wall");
    const fanCut = requiredCircleCut(sidePanel, "fan");
    const screwCut = requiredCircleCut(sidePanel, "screw");
    const fingerSlot = requiredRectCut(sidePanel, "finger-hole");

    expect(firstPanel.sheet.x).toBe(secondPanel.sheet.x);
    expect(secondPanel.sheet.y).toBeGreaterThan(firstPanel.sheet.y + firstPanel.height);
    expect(layout.cutSheet.width).toBeLessThan(700);
    expect(layout.cutSheet.height).toBeGreaterThan(1250);
    expect(fanCut.radius).toBeCloseTo((defaultSettings.fanDiameter - 4) / 2 - defaultSettings.kerfFit);
    expect(screwCut.radius).toBeCloseTo(defaultSettings.screwHoleDiameter / 2 - defaultSettings.kerfFit);
    expect(Math.min(fingerSlot.width, fingerSlot.height)).toBeCloseTo(
      defaultSettings.materialThickness - 2 * defaultSettings.kerfFit,
    );
  });

  test("can hide installed filter media without changing the cut sheet", () => {
    const withFilters = createLayout({ ...defaultSettings, showFilterMedia: true, showFans: true });
    const withoutFilters = createLayout({ ...defaultSettings, showFilterMedia: false, showFans: false });
    const encoded = encodeSettings(withoutFilters.rawSettings);

    expect(withoutFilters.rawSettings.showFilterMedia).toBe(false);
    expect(withoutFilters.rawSettings.showFans).toBe(false);
    expect(withoutFilters.cutSheet).toEqual(withFilters.cutSheet);
    expect(decodeSettings(encoded).showFilterMedia).toBe(false);
    expect(decodeSettings(encoded).showFans).toBe(false);
  });

  test("uses purchasable filter presets while preserving custom measured dimensions", () => {
    const luggablePreset = requiredFilterPreset("merv13-20x25x1");
    const luggableSettings = createLayout(applyFilterPreset(defaultSettings, luggablePreset.id)).rawSettings;

    expect(luggableSettings.filterPreset).toBe("merv13-20x25x1");
    expect(luggableSettings.filterWidth).toBeCloseTo(luggablePreset.dimensions.width);
    expect(luggableSettings.filterDepth).toBeCloseTo(luggablePreset.dimensions.depth);
    expect(luggableSettings.filterThickness).toBeCloseTo(luggablePreset.dimensions.thickness);

    const customSettings = decodeSettings("filterWidth=300&filterDepth=240&filterThickness=22");
    expect(customSettings.filterPreset).toBe(customFilterPresetId);
    expect(customSettings.filterWidth).toBe(300);
    expect(customSettings.filterDepth).toBe(240);
    expect(customSettings.filterThickness).toBe(22);

    const encodedCustom = encodeSettings(customSettings);
    expect(decodeSettings(encodedCustom).filterPreset).toBe(customFilterPresetId);
  });

  test("keeps URL boundary parsing valid for booleans, fan counts, and constrained rims", () => {
    const malformedBoolean = decodeSettings("showFans=maybe");
    const explicitFalse = decodeSettings("showFans=0");
    const highFanCount = decodeSettings("fansLeft=8");
    const smallCustomLayout = createLayout({
      ...defaultSettings,
      filterPreset: customFilterPresetId,
      filterWidth: 120,
      filterDepth: 120,
      materialThickness: 9,
      rim: 90,
    });

    expect(malformedBoolean.showFans).toBe(defaultSettings.showFans);
    expect(explicitFalse.showFans).toBe(false);
    expect(highFanCount.fansLeft).toBe(8);
    expect(smallCustomLayout.rawSettings.rim).toBeLessThanOrEqual((smallCustomLayout.summary.workingDepth - 1) / 2);
    expect(smallCustomLayout.cutPanels.every((panel) => panel.width > 0 && panel.height > 0)).toBe(true);
  });

  test("rejects unknown edge pattern characters instead of cutting plain edges silently", () => {
    expect(() => edgeSections("fx")).toThrow("Unknown edge");
  });

  test("keeps boundary settings separate from the structured build configuration", () => {
    const layout = createLayout(defaultSettings);
    const draftPanels = createAirPurifierCutPanels(layout.configuration);

    expect(layout.rawSettings.filterWidth).toBe(filterSelectionDimensions(layout.configuration.filter).width);
    expect(layout.configuration.filter.type).toBe("preset");
    expect(layout.configuration.fan.banks.left.type).toBe("auto");
    expect(layout.configuration.frameConstruction.type).toBe("split-rails");
    expect(layout.configuration.cutting.referenceScale).toEqual({ type: "enabled", length: 100 });
    expect(layout.summary.resolvedFans).toEqual({ left: 3, right: 3, top: 0, bottom: 0 });
    expect("sheet" in draftPanels[0]!).toBe(false);
    expect(layout.cutPanels.every((panel) => panel.sheet.x >= 0 && panel.sheet.y >= 0)).toBe(true);
  });

  test("keeps preset dimensions derived from the preset id", () => {
    const normalized = normalizeSettings(defaultSettings);
    const normalizedAgain = normalizeSettings(normalized);
    const dimensions = filterSelectionDimensions(normalized.filter);

    expect(normalized.filter).toEqual({ type: "preset", presetId: "merv13-20x25x1" });
    expect(dimensions).toEqual({
      width: defaultSettings.filterWidth,
      depth: defaultSettings.filterDepth,
      thickness: defaultSettings.filterThickness,
    });
    Object.assign(dimensions, { width: 1 });
    expect(filterSelectionDimensions(normalized.filter).width).toBe(defaultSettings.filterWidth);
    expect(normalizedAgain).toEqual(normalized);
  });

  test("aligns filter finger-hole rows with the matching perimeter teeth", () => {
    const layout = createLayout(defaultSettings);
    const frontWall = requiredPanel(layout.cutPanels, "bottom-fan-wall");
    const leftWall = requiredPanel(layout.cutPanels, "left-side-wall");
    const rightWall = requiredPanel(layout.cutPanels, "right-side-wall");

    expectHorizontalFingerHoleRowsToMatchEdges(frontWall);
    expectHorizontalFingerHoleRowsToMatchEdges(leftWall);
    expectHorizontalFingerHoleRowsToMatchEdges(rightWall);
  });

  test("builds explicit assembly parts for walls, filter frames, media, and dimensions", () => {
    const layout = createLayout(defaultSettings);
    const assembly = createAssemblyModel(layout);
    const frontRailPanel = requiredPanel(layout.cutPanels, "filter-1-front-long-rail");
    const frontRail = assembly.filterRails.find((part) => part.id === "filter-1-front-long-rail");
    const innerRail = assembly.filterRails.find((part) => part.id === "filter-1-inner-long-rail");
    const lowerFilterY = -layout.summary.chamberHeight / 2 + defaultSettings.filterThickness / 2;
    const upperFilterY = layout.summary.chamberHeight / 2 - defaultSettings.filterThickness / 2;
    const lowerOuterFrameY = -layout.summary.chamberHeight / 2 + defaultSettings.materialThickness / 2;
    const lowerInnerFrameY =
      -layout.summary.chamberHeight / 2 + defaultSettings.filterThickness + defaultSettings.materialThickness / 2;

    expect(assembly.panels.map((part) => part.role).sort()).toEqual([
      "front-fan-wall",
      "left-side-wall",
      "rear-fan-wall",
      "right-side-wall",
    ]);
    expect(assembly.filterRails).toHaveLength(16);
    expect(assembly.filterRails.every((part) => part.role === "filter-rail" && part.panel.outline.length > 4)).toBe(true);
    expect(assembly.filterFrames).toHaveLength(8);
    expect(assembly.filterMedia).toHaveLength(2);
    expect(assembly.seams).toHaveLength(12);
    expect(assembly.dimensions.map((dimension) => dimension.label)).toEqual(["A", "B", "C", "E", "G"]);
    expect(assembly.dimensions[0]?.measurement).toEqual({ value: layout.rawSettings.filterWidth, description: "filter width" });
    expect(assembly.dimensions.every((dimension) => dimension.labelOffset.length === 3)).toBe(true);
    expect(frontRailPanel.assembly).toEqual({ type: "filter-rail", filterIndex: 0, railKey: "front-long" });
    expect(frontRail?.position[1]).toBeCloseTo(lowerOuterFrameY);
    expect(frontRail?.position[2]).toBeCloseTo(-layout.summary.workingDepth / 2 + defaultSettings.rim / 2);
    expect(frontRail?.rotation).toEqual([Math.PI / 2, 0, 0]);
    expect(innerRail?.position[1]).toBeCloseTo(lowerInnerFrameY);
    expect(innerRail?.position[2]).toBeCloseTo(-layout.summary.workingDepth / 2 + defaultSettings.rim / 2);
    expect(innerRail?.rotation).toEqual([Math.PI / 2, 0, 0]);
    expect(assembly.filterMedia[0]?.position[1]).toBeCloseTo(lowerFilterY);
    expect(assembly.filterMedia[1]?.position[1]).toBeCloseTo(upperFilterY);
    expect(assembly.filterMedia[0]?.size[0]).toBeCloseTo(defaultSettings.filterWidth);
    expect(assembly.filterMedia[0]?.size[1]).toBeCloseTo(defaultSettings.filterThickness);
    expect(assembly.filterMedia[0]?.size[2]).toBeCloseTo(defaultSettings.filterDepth);
  });

  test("assembles unsplit filter frame panels on horizontal filter faces", () => {
    const layout = createLayout({ ...defaultSettings, splitFrames: false });
    const assembly = createAssemblyModel(layout);
    const lowerOuterFrameY = -layout.summary.chamberHeight / 2 + defaultSettings.materialThickness / 2;
    const lowerInnerFrameY =
      -layout.summary.chamberHeight / 2 + defaultSettings.filterThickness + defaultSettings.materialThickness / 2;
    const frontFrame = assembly.filterRails.find((part) => part.id === "filter-1-front-frame");
    const rearFrame = assembly.filterRails.find((part) => part.id === "filter-1-rear-frame");

    expect(assembly.filterRails).toHaveLength(4);
    expect(frontFrame?.role).toBe("filter-frame-panel");
    expect(frontFrame?.position[0]).toBe(0);
    expect(frontFrame?.position[1]).toBeCloseTo(lowerOuterFrameY);
    expect(frontFrame?.position[2]).toBe(0);
    expect(rearFrame?.position[0]).toBe(0);
    expect(rearFrame?.position[1]).toBeCloseTo(lowerInnerFrameY);
    expect(rearFrame?.position[2]).toBe(0);
    expect(frontFrame?.rotation).toEqual([Math.PI / 2, 0, 0]);
    expect(rearFrame?.rotation).toEqual([Math.PI / 2, 0, 0]);
  });

  test("assembles the one-filter closed back as the opposite horizontal face", () => {
    const layout = createLayout({ ...defaultSettings, filters: 1 });
    const assembly = createAssemblyModel(layout);
    const closedBack = assembly.panels.find((part) => part.id === "closed-back-panel");
    const closedBackY = layout.summary.chamberHeight / 2 - defaultSettings.materialThickness / 2;
    const filterMedia = assembly.filterMedia.find((part) => part.id === "filter-media-1");

    expect(closedBack?.role).toBe("closed-back");
    expect(closedBack?.position[0]).toBe(0);
    expect(closedBack?.position[1]).toBeCloseTo(closedBackY);
    expect(closedBack?.position[2]).toBe(0);
    expect(closedBack?.rotation).toEqual([Math.PI / 2, 0, 0]);
    expect(filterMedia?.size).toEqual([
      defaultSettings.filterWidth,
      defaultSettings.filterThickness,
      defaultSettings.filterDepth,
    ]);
  });

  test("keeps one-filter top teeth aligned around the closed-back face", () => {
    const layout = createLayout({ ...defaultSettings, filters: 1 });
    const assembly = createAssemblyModel(layout);
    const frontWall = requiredAssemblyPanel(assembly, "bottom-fan-wall");
    const rearWall = requiredAssemblyPanel(assembly, "top-fan-wall");
    const leftWall = requiredAssemblyPanel(assembly, "left-side-wall");
    const rightWall = requiredAssemblyPanel(assembly, "right-side-wall");

    expect(panelTopToothY(rearWall)).toBeCloseTo(panelTopToothY(frontWall));
    expect(panelTopToothY(leftWall)).toBeCloseTo(panelTopToothY(frontWall));
    expect(panelTopToothY(rightWall)).toBeCloseTo(panelTopToothY(frontWall));
  });

  test("reports export readiness warnings before drawing export", () => {
    const defaultLayout = createLayout(defaultSettings);
    expect(evaluateBuildDiagnostics(defaultLayout)).toEqual([]);
    expect(summarizeBuildReadiness(defaultLayout).severity).toBe("info");

    const noFanLayout = createLayout({
      ...defaultSettings,
      fansLeft: 0,
      fansRight: 0,
      fansTop: 0,
      fansBottom: 0,
    });
    expect(evaluateBuildDiagnostics(noFanLayout).map((diagnostic) => diagnostic.id)).toContain("no-fans");

    const customLayout = createLayout({
      ...defaultSettings,
      filterPreset: customFilterPresetId,
      filterWidth: 130,
      filterDepth: 130,
      filterThickness: 10,
    });
    expect(evaluateBuildDiagnostics(customLayout).map((diagnostic) => diagnostic.id)).toContain("custom-filter-range");
  });

  test("splits printable kits to fit common desktop printer beds", () => {
    const layout = createLayout(defaultSettings);
    const boundedPresetIds = printVolumePresets
      .filter((preset) => preset.bed.type === "bounded")
      .map((preset) => preset.id);

    expect(boundedPresetIds).toEqual([
      "bed-180",
      "bed-220",
      "bed-225",
      "bed-prusa-mk",
      "bed-256",
      "bed-300",
      "bed-h2-safe",
      "bed-350",
      "bed-prusa-xl",
      "bed-420",
    ] satisfies readonly PrintVolumePresetId[]);

    for (const presetId of boundedPresetIds) {
      const kit = createPrintableKit(layout, presetId);

      expect(kit.summary.partCount).toBeGreaterThan(layout.cutPanels.length);
      expect(kit.summary.splitPanelCount).toBeGreaterThan(0);
      expect(kit.summary.glueKeyCount).toBeGreaterThan(0);
      expect(kit.summary.oversizedPartCount).toBe(0);
      expect(kit.summary.retainedPrintCriticalCutFeatureCount).toBe(kit.summary.sourcePrintCriticalCutFeatureCount);
      expect(kit.parts.every((part) => partFitsPrintBed(part, kit.preset.bed))).toBe(true);
      expect(kit.parts.some((part) => part.kind === "dovetail-glue-key")).toBe(true);
    }
  });

  test("keeps the 256 mm print bed as the default and redirects the legacy 320 mm URL", () => {
    expect(findPrintVolumePreset(null).id).toBe("bed-256");
    expect(findPrintVolumePreset("bed-320").id).toBe("bed-h2-safe");
  });

  test("keeps the unsplit print preset as one printable part per cut panel", () => {
    const layout = createLayout(defaultSettings);
    const kit = createPrintableKit(layout, "unsplit");

    expect(kit.summary.partCount).toBe(layout.cutPanels.length);
    expect(kit.summary.panelTileCount).toBe(layout.cutPanels.length);
    expect(kit.summary.glueKeyCount).toBe(0);
    expect(kit.summary.splitPanelCount).toBe(0);
    expect(kit.summary.oversizedPartCount).toBe(0);
    expect(kit.summary.retainedCutFeatureCount).toBe(kit.summary.sourceCutFeatureCount);
    expect(kit.summary.retainedPrintCriticalCutFeatureCount).toBe(kit.summary.sourcePrintCriticalCutFeatureCount);
  });

  test("exports a browser-native 3MF print package", () => {
    const layout = createLayout(defaultSettings);
    const printExport = createPrintableThreeMfExport(layout, "bed-h2-safe");
    const content = new TextDecoder("latin1").decode(printExport.bytes);

    expect(printExport.filename).toBe("nukit-open-air-purifier-print-kit.3mf");
    expect(printExport.mimeType).toBe("model/3mf");
    expect(printExport.bytes[0]).toBe(0x50);
    expect(printExport.bytes[1]).toBe(0x4b);
    expect(content).toContain("[Content_Types].xml");
    expect(content).toContain("3D/3dmodel.model");
    expect(content).toContain('<model unit="millimeter"');
    expect(content).toContain("dovetail glue key");
    expect(printExport.kit.preset.id).toBe("bed-h2-safe");
  });
});

function requiredFilterPreset(id: string) {
  const preset = filterPresets.find((entry) => entry.id === id);
  if (preset === undefined) {
    throw new Error(`requiredFilterPreset: Missing ${id}`);
  }
  return preset;
}

function readNumericSvgAttribute(svg: string, attribute: "width" | "height"): number {
  const match = svg.match(new RegExp(`${attribute}="([0-9.]+)mm"`));
  if (match === null) {
    throw new Error(`readNumericSvgAttribute: Missing ${attribute} attribute`);
  }
  return Number(match[1]);
}

function requiredPanel(panels: ReturnType<typeof createLayout>["cutPanels"], id: string) {
  const panel = panels.find((entry) => entry.id === id);
  if (panel === undefined) {
    throw new Error(`requiredPanel: Missing ${id}`);
  }
  return panel;
}

function requiredCircleCut(panel: ReturnType<typeof requiredPanel>, role: "fan" | "screw") {
  const cut = panel.cuts.find((entry) => entry.type === "circle" && entry.role === role);
  if (cut === undefined || cut.type !== "circle") {
    throw new Error(`requiredCircleCut: Missing ${role} on ${panel.id}`);
  }
  return cut;
}

function requiredRectCut(panel: ReturnType<typeof requiredPanel>, role: "finger-hole" | "slot" | "window") {
  const cut = panel.cuts.find((entry) => entry.type === "rect" && entry.role === role);
  if (cut === undefined || cut.type !== "rect") {
    throw new Error(`requiredRectCut: Missing ${role} on ${panel.id}`);
  }
  return cut;
}

function expectHorizontalFingerHoleRowsToMatchEdges(panel: ReturnType<typeof requiredPanel>): void {
  const rows = horizontalFingerHoleRows(panel);
  expect(rows).toHaveLength(2);

  rows.forEach((row, index) => {
    const edge = index === 0 ? "bottom" : "top";
    const edgeCenters = horizontalEdgeToothCenters(panel, edge);
    expect(row.centers).toHaveLength(edgeCenters.length);
    expect(maxAlignmentError(row.centers, edgeCenters)).toBeLessThan(0.001);
  });
}

function horizontalFingerHoleRows(panel: ReturnType<typeof requiredPanel>): Array<{ y: number; centers: number[] }> {
  const rows = new Map<string, { y: number; centers: number[] }>();
  for (const cut of panel.cuts) {
    if (cut.type !== "rect" || cut.role !== "finger-hole") {
      continue;
    }

    const y = roundCoordinate(cut.y + cut.height / 2);
    const key = String(y);
    const row = rows.get(key) ?? { y, centers: [] };
    row.centers.push(roundCoordinate(cut.x + cut.width / 2));
    rows.set(key, row);
  }

  return Array.from(rows.values())
    .filter((row) => row.centers.length > 1)
    .map((row) => ({
      y: row.y,
      centers: row.centers.sort((left, right) => left - right),
    }))
    .sort((left, right) => left.y - right.y);
}

function horizontalEdgeToothCenters(panel: ReturnType<typeof requiredPanel>, edge: "bottom" | "top"): number[] {
  const edgeY =
    edge === "bottom"
      ? Math.min(...panel.outline.map((point) => point.y))
      : Math.max(...panel.outline.map((point) => point.y));
  const centers: number[] = [];

  for (let index = 0; index < panel.outline.length; index += 1) {
    const first = panel.outline[index];
    const second = panel.outline[(index + 1) % panel.outline.length];
    if (first === undefined || second === undefined) {
      continue;
    }
    if (Math.abs(first.y - edgeY) > 0.001 || Math.abs(second.y - edgeY) > 0.001) {
      continue;
    }
    if (Math.abs(first.x - second.x) < 0.001) {
      continue;
    }

    centers.push(roundCoordinate((first.x + second.x) / 2));
  }

  return centers.sort((left, right) => left - right);
}

function maxAlignmentError(left: readonly number[], right: readonly number[]): number {
  return left.reduce((maxError, value, index) => Math.max(maxError, Math.abs(value - (right[index] ?? value))), 0);
}

function requiredAssemblyPanel(assembly: ReturnType<typeof createAssemblyModel>, id: string) {
  const panel = [...assembly.panels, ...assembly.filterRails].find((part) => part.id === id);
  if (panel === undefined) {
    throw new Error(`requiredAssemblyPanel: Missing ${id}`);
  }
  return panel;
}

function panelTopToothY(part: ReturnType<typeof requiredAssemblyPanel>): number {
  const top = Math.max(...part.panel.outline.map((point) => point.y));
  return roundCoordinate(part.position[1] + top - part.panel.assemblyCenter.y);
}

function roundCoordinate(value: number): number {
  return Number(value.toFixed(6));
}
