import { describe, expect, test } from "bun:test";
import { defaultSettings } from "@/domain/purifier/airPurifier";
import { createLaserSvg, createLayout } from "@/fabrication/purifierLayout";
import { filterSelectionDimensions } from "@/domain/purifier/filter";
import { createAirPurifierCutPanels } from "@/fabrication/laser/panels";
import { edgeSections } from "@/fabrication/laser/cutGeometry";
import { generateAirPurifier } from "@/ports/boxes/generators/airPurifier";

describe("Air purifier cut-sheet equivalence", () => {
  test("uses the generated Boxes document for summary and SVG output", () => {
    const layout = createLayout(defaultSettings);
    const svg = createLaserSvg(layout);

    expect(layout.summary.sheetWidth).toBe(layout.cutSheet.width);
    expect(layout.summary.sheetHeight).toBe(layout.cutSheet.height);
    expect(svg).toContain("<svg");
    expect(svg).toContain("Generated by the TypeScript Boxes.py port layer.");
    expect(svg).toContain('inkscape:label="Cut outer profiles"');
    expect(svg).toContain('data-operation="engrave"');
    expect(svg).toContain("100.0mm, burn:0.10mm");
    expect(readNumericSvgAttribute(svg, "width")).toBeCloseTo(layout.cutSheet.width);
    expect(readNumericSvgAttribute(svg, "height")).toBeCloseTo(layout.cutSheet.height);
  });

  test("keeps the legacy Boxes.py-compatible generator available for audits", () => {
    const generator = generateAirPurifier(defaultSettings);
    const document = generator.toDocument();
    const circles = document.shapes.filter((shape) => shape.type === "circle");
    const cutRects = document.shapes.filter((shape) => shape.type === "rect" && shape.color === "cut");
    const slotRects = document.shapes.filter((shape) => shape.type === "rect" && shape.color === "inner-cut");

    expect(circles).toHaveLength(30);
    expect(cutRects.length).toBeGreaterThanOrEqual(20);
    expect(slotRects.length).toBeGreaterThan(120);
  });

  test("uses cut panel outlines as the SVG and 3D preview source of truth", () => {
    const layout = createLayout(defaultSettings);
    const svg = createLaserSvg(layout);
    const outerPathShapes = layout.cutSheet.shapes.filter((shape) => shape.type === "path" && shape.color === "cut");
    const innerPathShapes = layout.cutSheet.shapes.filter((shape) => shape.type === "path" && shape.color === "inner-cut");
    const fanPanels = layout.cutPanels.filter((panel) => panel.cuts.some((cut) => cut.type === "circle" && cut.role === "fan"));
    const assembledPanels = layout.cutPanels.filter(
      (panel) => panel.assembly?.type === "placed" && panel.assembly.role !== "filter-frame-panel",
    );

    expect(outerPathShapes).toHaveLength(layout.cutPanels.length);
    expect(innerPathShapes.length).toBeGreaterThan(280);
    expect(layout.cutSheet.shapes.some((shape) => shape.type === "circle" || shape.type === "rect")).toBe(false);
    expect(svg).toContain("<path");
    expect(fanPanels).toHaveLength(2);
    expect(assembledPanels.map((panel) => panel.id).sort()).toEqual([
      "bottom-fan-wall",
      "left-side-wall",
      "right-side-wall",
      "top-fan-wall",
    ]);
    expect(layout.cutPanels.every((panel) => panel.outline.length > 4)).toBe(true);
  });

  test("matches upstream AirPurifier layout direction and burn-corrected inner cuts", () => {
    const layout = createLayout(defaultSettings);
    const firstPanel = layout.cutPanels[0];
    const secondPanel = layout.cutPanels[1];
    const sidePanel = requiredPanel(layout.cutPanels, "left-side-wall");
    const fanCut = requiredCircleCut(sidePanel, "fan");
    const screwCut = requiredCircleCut(sidePanel, "screw");
    const fingerSlot = requiredRectCut(sidePanel, "finger-hole");

    expect(firstPanel?.sheet.x).toBe(secondPanel?.sheet.x);
    expect(secondPanel?.sheet.y).toBeGreaterThan((firstPanel?.sheet.y ?? 0) + (firstPanel?.height ?? 0));
    expect(layout.cutSheet.width).toBeLessThan(700);
    expect(layout.cutSheet.height).toBeGreaterThan(1250);
    expect(fanCut.radius).toBeCloseTo((defaultSettings.fanDiameter - 4) / 2 - defaultSettings.kerfFit);
    expect(screwCut.radius).toBeCloseTo(defaultSettings.screwHoleDiameter / 2 - defaultSettings.kerfFit);
    expect(Math.min(fingerSlot.width, fingerSlot.height)).toBeCloseTo(
      defaultSettings.materialThickness - 2 * defaultSettings.kerfFit,
    );
  });

  test("rejects unknown edge pattern characters instead of cutting plain edges silently", () => {
    expect(() => edgeSections("fx")).toThrow("Unknown edge");
  });

  test("keeps boundary settings separate from the structured build configuration", () => {
    const layout = createLayout(defaultSettings);
    const draftPanels = createAirPurifierCutPanels(layout.configuration);

    expect(layout.rawSettings.filterWidth).toBe(filterSelectionDimensions(layout.configuration.filter).width);
    expect(layout.configuration.filter.type).toBe("preset");
    expect(layout.configuration.design.type).toBe("laser-derived-printable-kit");
    expect(
      layout.configuration.design.type === "laser-derived-printable-kit"
        ? layout.configuration.design.fanBanks.left
        : undefined,
    ).toEqual({ type: "auto" });
    expect(layout.configuration.fan.banks.left.type).toBe("auto");
    expect(layout.configuration.frameConstruction.type).toBe("split-rails");
    expect(layout.configuration.preview.enclosure.autoRotate).toBe(true);
    expect(layout.configuration.preview.printSheets.showPlateLabels).toBe(false);
    expect(layout.configuration.preview.cutSheet.referenceScale).toEqual({ type: "enabled", length: 100 });
    expect(layout.configuration.cutting.referenceScale).toEqual({ type: "enabled", length: 100 });
    expect(layout.summary.resolvedFans).toEqual({ left: 3, right: 3, top: 0, bottom: 0 });
    expect("sheet" in draftPanels[0]!).toBe(false);
    expect(layout.cutPanels.every((panel) => panel.sheet.x >= 0 && panel.sheet.y >= 0)).toBe(true);
  });

  test("aligns filter finger-hole rows with the matching perimeter teeth", () => {
    const layout = createLayout(defaultSettings);
    const frontWall = requiredPanel(layout.cutPanels, "bottom-fan-wall");
    const leftWall = requiredPanel(layout.cutPanels, "left-side-wall");
    const rightWall = requiredPanel(layout.cutPanels, "right-side-wall");

    expectHorizontalFingerHoleRowsToMatchEdges(frontWall);
    expectHorizontalFingerHoleRowsToMatchEdges(leftWall);
    expectHorizontalFingerHoleRowsToMatchEdges(rightWall);
  });
});

function readNumericSvgAttribute(svg: string, attribute: "width" | "height"): number {
  const match = svg.match(new RegExp(`${attribute}="([0-9.]+)mm"`));
  if (match === null) {
    throw new Error(`readNumericSvgAttribute: Missing ${attribute} attribute`);
  }
  return Number(match[1]);
}

function requiredPanel(panels: ReturnType<typeof createLayout>["cutPanels"], id: string) {
  const panel = panels.find((entry) => entry.id === id);
  if (panel === undefined) {
    throw new Error(`requiredPanel: Missing ${id}`);
  }
  return panel;
}

function requiredCircleCut(panel: ReturnType<typeof requiredPanel>, role: "fan" | "screw") {
  const cut = panel.cuts.find((entry) => entry.type === "circle" && entry.role === role);
  if (cut === undefined || cut.type !== "circle") {
    throw new Error(`requiredCircleCut: Missing ${role} on ${panel.id}`);
  }
  return cut;
}

function requiredRectCut(panel: ReturnType<typeof requiredPanel>, role: "finger-hole" | "slot" | "window") {
  const cut = panel.cuts.find((entry) => entry.type === "rect" && entry.role === role);
  if (cut === undefined || cut.type !== "rect") {
    throw new Error(`requiredRectCut: Missing ${role} on ${panel.id}`);
  }
  return cut;
}

function expectHorizontalFingerHoleRowsToMatchEdges(panel: ReturnType<typeof requiredPanel>): void {
  const rows = horizontalFingerHoleRows(panel);
  expect(rows).toHaveLength(2);

  rows.forEach((row, index) => {
    const edge = index === 0 ? "bottom" : "top";
    const edgeCenters = horizontalEdgeToothCenters(panel, edge);
    expect(row.centers).toHaveLength(edgeCenters.length);
    expect(maxAlignmentError(row.centers, edgeCenters)).toBeLessThan(0.001);
  });
}

function horizontalFingerHoleRows(panel: ReturnType<typeof requiredPanel>): Array<{ y: number; centers: number[] }> {
  const rows = new Map<string, { y: number; centers: number[] }>();
  for (const cut of panel.cuts) {
    if (cut.type !== "rect" || cut.role !== "finger-hole") {
      continue;
    }

    const y = roundCoordinate(cut.y + cut.height / 2);
    const key = String(y);
    const row = rows.get(key) ?? { y, centers: [] };
    row.centers.push(roundCoordinate(cut.x + cut.width / 2));
    rows.set(key, row);
  }

  return Array.from(rows.values())
    .filter((row) => row.centers.length > 1)
    .map((row) => ({
      y: row.y,
      centers: row.centers.sort((left, right) => left - right),
    }))
    .sort((left, right) => left.y - right.y);
}

function horizontalEdgeToothCenters(panel: ReturnType<typeof requiredPanel>, edge: "bottom" | "top"): number[] {
  const edgeY =
    edge === "bottom"
      ? Math.min(...panel.outline.map((point) => point.y))
      : Math.max(...panel.outline.map((point) => point.y));
  const centers: number[] = [];

  for (let index = 0; index < panel.outline.length; index += 1) {
    const first = panel.outline[index];
    const second = panel.outline[(index + 1) % panel.outline.length];
    if (first === undefined || second === undefined) {
      continue;
    }
    if (Math.abs(first.y - edgeY) > 0.001 || Math.abs(second.y - edgeY) > 0.001) {
      continue;
    }
    if (Math.abs(first.x - second.x) < 0.001) {
      continue;
    }

    centers.push(roundCoordinate((first.x + second.x) / 2));
  }

  return centers.sort((left, right) => left - right);
}

function maxAlignmentError(left: readonly number[], right: readonly number[]): number {
  return left.reduce((maxError, value, index) => Math.max(maxError, Math.abs(value - (right[index] ?? value))), 0);
}

function roundCoordinate(value: number): number {
  return Number(value.toFixed(6));
}
